In [2]:
import pandas
import requests
import numpy as np

In [4]:
array=np.array([1,2,3,4])

In [5]:
print(array)

[1 2 3 4]


In [6]:
array

array([1, 2, 3, 4])

In [12]:
b=np.array([4.6,7.9,3.2])

In [13]:
b

array([4.6, 7.9, 3.2])

In [15]:
array.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')